# ==============================================================================
# ERAVAULT - MULTI-STAGE PRODUCTION DOCKERFILE (Next.js 15 Standalone)
# ==============================================================================

# ------------------------------------------------------------------------------
# STAGE 1: Base Alpine Linux Image
# ------------------------------------------------------------------------------
FROM node:20-alpine AS base
WORKDIR /app
# Install libc6-compat for native Node modules (if needed by underlying libs)
RUN apk add --no-cache libc6-compat

# ------------------------------------------------------------------------------
# STAGE 2: Install Dependencies
# ------------------------------------------------------------------------------
FROM base AS deps
COPY package.json package-lock.json* ./
# Install dependencies cleanly using lockfile
RUN npm ci

# ------------------------------------------------------------------------------
# STAGE 3: Builder (Compile Next.js & Bake Client-Side Env Vars)
# ------------------------------------------------------------------------------
FROM base AS builder
WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Disable Next.js anonymous telemetry during build
ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=production

# --- BUILD-TIME CLIENT ENVIRONMENT VARIABLES ---
# Next.js embeds NEXT_PUBLIC_* variables into the static bundle during `npm run build`.
# We pass them as ARGs so they are available when compilation runs.
ARG NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
ARG NEXT_PUBLIC_CLERK_SIGN_IN_URL=/sign-in
ARG NEXT_PUBLIC_CLERK_SIGN_UP_URL=/sign-up
ARG NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL=/dashboard
ARG NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL=/dashboard
ARG NEXT_PUBLIC_IMGBB_API_KEY

ENV NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=$NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
ENV NEXT_PUBLIC_CLERK_SIGN_IN_URL=$NEXT_PUBLIC_CLERK_SIGN_IN_URL
ENV NEXT_PUBLIC_CLERK_SIGN_UP_URL=$NEXT_PUBLIC_CLERK_SIGN_UP_URL
ENV NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL=$NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL
ENV NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL=$NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL
ENV NEXT_PUBLIC_IMGBB_API_KEY=$NEXT_PUBLIC_IMGBB_API_KEY

# Run the build (generates .next/standalone because of next.config.ts)
RUN npm run build

# ------------------------------------------------------------------------------
# STAGE 4: Minimal Production Runner
# ------------------------------------------------------------------------------
FROM base AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

# Create a secure, unprivileged system user to run the container
RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nextjs

# Copy only the compiled standalone output and static assets from the builder stage
COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

# Switch to the non-root user for enterprise-grade container security
USER nextjs

EXPOSE 3000

# Start the standalone Node server generated by Next.js
CMD ["node", "server.js"]